[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/"
  to = "https://arlingtoncentralchurch.com"
  status = 301
  force = true
