backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/materials/index.md"
        label: "Materials"
        name: "materials"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "materials-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - label: "File Link"
                name: "link"
                widget: "string"
              - label: "File Title"
                name: "title"
                widget: "string"
              - label: "File Description"
                name: "desc"
                widget: "string"